//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataSources.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        internal static string Customer_DisplayName_AddressLine1 {
            get {
                return ResourceManager.GetString("Customer_DisplayName_AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string Customer_DisplayName_AddressLine2 {
            get {
                return ResourceManager.GetString("Customer_DisplayName_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Customer_DisplayName_City {
            get {
                return ResourceManager.GetString("Customer_DisplayName_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No.
        /// </summary>
        internal static string Customer_DisplayName_CustomerNumber {
            get {
                return ResourceManager.GetString("Customer_DisplayName_CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Customer_DisplayName_Email {
            get {
                return ResourceManager.GetString("Customer_DisplayName_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Customer_DisplayName_FirstName {
            get {
                return ResourceManager.GetString("Customer_DisplayName_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string Customer_DisplayName_IDCustomerName {
            get {
                return ResourceManager.GetString("Customer_DisplayName_IDCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Customer_DisplayName_LastName {
            get {
                return ResourceManager.GetString("Customer_DisplayName_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Code.
        /// </summary>
        internal static string Customer_DisplayName_PostalCode {
            get {
                return ResourceManager.GetString("Customer_DisplayName_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Customer_DisplayName_State {
            get {
                return ResourceManager.GetString("Customer_DisplayName_State", resourceCulture);
            }
        }
    }
}
